name: material_design_icons_flutter
description: A stub that redirects to flutter_material_design_icons to prevent final class compiler errors on web.
version: 7.0.7296
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_material_design_icons: ^3.0.0
