import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:arcane/src/services/ai_service.dart';
import 'package:arcane/src/services/firebase_service.dart' as fb_service;
import 'package:arcane/src/services/local_storage_service.dart';
import 'package:arcane/src/services/storage_service.dart';
import 'package:arcane/src/services/data_export_service.dart';
import 'package:arcane/src/utils/helpers.dart' as helper;
import 'package:arcane/src/utils/history_helper.dart'; 
import 'package:arcane/src/utils/constants.dart';
import 'package:arcane/src/models/app_state_models.dart';
import 'package:arcane/src/models/task_models.dart';
import 'package:arcane/src/models/project_models.dart';
import 'package:arcane/src/models/skill_models.dart';
import 'package:arcane/src/models/chatbot_models.dart';
import 'package:arcane/src/models/finance_models.dart';
import 'package:intl/intl.dart';
import 'package:collection/collection.dart';
import 'package:uuid/uuid.dart';
import 'dart:io';
import 'dart:convert';
import 'package:firebase_auth/firebase_auth.dart';

// Import Mixins
import 'package:arcane/src/providers/mixins/sync_mixin.dart';
import 'package:arcane/src/providers/mixins/task_mixin.dart';
import 'package:arcane/src/providers/mixins/finance_mixin.dart';
import 'package:arcane/src/providers/mixins/user_mixin.dart';

// Import Actions
import 'package:arcane/src/providers/actions/task_actions.dart';
import 'package:arcane/src/providers/actions/ai_generation_actions.dart';
import 'package:arcane/src/providers/actions/timer_actions.dart';
import 'package:arcane/src/providers/actions/project_actions.dart';
import 'package:arcane/src/providers/actions/report_actions.dart';
import 'package:arcane/src/providers/actions/schedule_actions.dart';
import 'package:arcane/src/providers/actions/finance_actions.dart';
import 'package:arcane/src/providers/actions/journaling_actions.dart';

class AppProvider with ChangeNotifier, SyncMixin, TaskMixin, FinanceMixin, UserMixin, WidgetsBindingObserver {
  
  final AIService _aiService = AIService();
  final DataExportService _exportService = DataExportService();
  final StorageService _cloudStorage = StorageService();
  final LocalStorageService _localStorage = LocalStorageService();

  AIService get aiService => _aiService;

  // UI State
  String? _loadingTaskName;
  String? get loadingTaskName => _loadingTaskName;
  bool _isGeneratingSubquestsForTask = false;
  bool get isGeneratingSubquests => _isGeneratingSubquestsForTask;
  
  bool get isDataLoadingAfterLogin => false; 

  // Actions
  late final TaskActions _taskActions;
  late final AIGenerationActions _aiGenerationActions;
  late final TimerActions _timerActions;
  late final ProjectActions _projectActions;
  late final ReportActions _reportActions;
  late final ScheduleActions _scheduleActions;
  late final FinanceActions _financeActions;
  late final JournalingActions _journalingActions;

  TaskActions get taskActions => _taskActions;
  AIGenerationActions get aiGenerationActions => _aiGenerationActions;
  TimerActions get timerActions => _timerActions;
  ProjectActions get projectActions => _projectActions;
  ReportActions get reportActions => _reportActions;
  ScheduleActions get scheduleActions => _scheduleActions;
  FinanceActions get financeActions => _financeActions;
  JournalingActions get journalingActions => _journalingActions;

  AppProvider() {
    _taskActions = TaskActions(this);
    _aiGenerationActions = AIGenerationActions(this);
    _timerActions = TimerActions(this);
    _projectActions = ProjectActions(this);
    _reportActions = ReportActions(this);
    _scheduleActions = ScheduleActions(this);
    _financeActions = FinanceActions(this);
    _journalingActions = JournalingActions(this);

    _initialize();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.paused || state == AppLifecycleState.inactive) {
      if (currentUser != null) {
        scheduleRealtimeSync(); 
      }
    } else if (state == AppLifecycleState.resumed) {
      if (currentUser != null) {
        // Recover any daily reports generated by other devices to prevent overwrite
        fetchDailyReportsFromCloud();
      }
    }
  }

  @override
  Future<void> manuallyLoadFromCloud() async {
    await super.manuallyLoadFromCloud();
    await fetchDailyReportsFromCloud();
  }

  // --- Initialization ---

  Future<void> _initialize() async {
    initializeSkills();
    initializeDefaultFinanceCategories();
    initSync(); 
    
    fb_service.authStateChanges.listen(_onAuthStateChanged);
  }

  Future<void> _onAuthStateChanged(User? user) async {
    if (authLoading && currentUser != null && user != null && currentUser!.uid == user.uid) return;

    setAuthLoading(true);

    if (user != null) {
      setCurrentUser(user);

      // Load Local
      final localData = await _localStorage.loadState();
      bool loadedLocal = false;
      if (localData != null) {
        loadStateFromMap(localData);
        loadedLocal = true;
        _cleanOverlappingSessions();
        _fixTimerAnomalies();
        _handleDailyReset();
        setAuthLoading(false); // Show UI immediately
      }

      // Sync with Cloud
      try {
        final cloudData = await _cloudStorage.getUserData(user.uid);
        if (cloudData != null) {
          int cloudTs = cloudData['settings']?['lastModified'] ?? 0;
          
          if (!loadedLocal || cloudTs > settings.lastModified) {
            loadStateFromMap(cloudData);
            scheduleRealtimeSync(); // Update local
          } else if (loadedLocal && settings.lastModified > cloudTs) {
            scheduleRealtimeSync(); // Push local to cloud
          }
        } else if (!loadedLocal) {
          await _resetToInitialState();
          setLastLoginDate(helper.getTodayDateString());
          scheduleRealtimeSync();
        }
        
        _cleanOverlappingSessions();
        _fixTimerAnomalies();
        await _taskActions.recalibrateTimeLogs(silent: true);
        _handleDailyReset();
        
        // Fetch specific daily subcollections to avoid cross-device history overwrite
        await fetchDailyReportsFromCloud();

      } catch (e) {
        debugPrint("Cloud init failed: $e");
      } finally {
        setAuthLoading(false);
      }

    } else {
      setCurrentUser(null);
      await _resetToInitialState();
      await _localStorage.clearState();
      setAuthLoading(false);
    }
  }

  Future<void> fetchDailyReportsFromCloud() async {
    if (currentUser == null) return;
    final recentDaily = await _cloudStorage.fetchRecentDailyData(currentUser!.uid, 14); 
    if (recentDaily.isNotEmpty) {
      final newHistory = Map<String, dynamic>.from(completedByDay);
      recentDaily.forEach((date, data) {
        final dayData = Map<String, dynamic>.from(newHistory[date] ?? {});
        bool changed = false;
        if (data.containsKey('briefing')) {
          dayData['aiBriefing'] = data['briefing'];
          changed = true;
        }
        if (data.containsKey('report')) {
          dayData['startDayReport'] = data['report'];
          changed = true;
        }
        if (changed) {
          newHistory[date] = dayData;
        }
      });
      setCompletedByDay(newHistory);
    }
  }

  Future<void> _resetToInitialState() async {
    setLastLoginDate(null);
    setSettings(AppSettings());
    setMainTasks(initialMainTaskTemplates.map((t) => MainTask.fromTemplate(t)).toList());
    setCompletedByDay({});
    setActiveTimers({});
    setReflectionLogs([]);
    setTransactions([]);
    setCategories([]);
    setSavingsGoals([]);
    setChatbotMemory(ChatbotMemory());
    initializeSkills();
    initializeDefaultFinanceCategories();
  }

  // --- Mixin Implementations & Legacy Compat ---

  @override
  Map<String, dynamic> getFullAppState() {
    final map = <String, dynamic>{};
    map.addAll(getTaskStateMap());
    map.addAll(getFinanceStateMap());
    map.addAll(getUserStateMap());
    return map;
  }

  // Legacy compatibility for DatabaseEditorScreen and DataRecoveryScreen
  Map<String, dynamic> getAppStateAsMap() => getFullAppState();
  
  // Legacy compatibility
  void loadAppStateFromMap(Map<String, dynamic> data) => loadStateFromMap(data);

  @override
  void loadStateFromMap(Map<String, dynamic> data) {
    loadTaskState(data);
    loadFinanceState(data);
    loadUserState(data);
    
    // Version Check
    if (settings.dataVersion < 1) {
      settings.dataVersion = 1;
      markDirty('settings');
    }
  }

  // --- UI Helpers ---

  void setLoadingTask(String? name) {
    _loadingTaskName = name;
    notifyListeners();
  }

  void setProviderAISubquestLoading(bool loading) {
    _isGeneratingSubquestsForTask = loading;
    notifyListeners();
  }

  void setProviderApiKeyIndex(int index) => setApiKeyIndex(index);

  // --- State Bridge ---
  
  void setProviderState({
      String? lastLoginDate,
      List<MainTask>? mainTasks,
      Map<String, dynamic>? completedByDay,
      Map<String, dynamic>? activeTimers,
      DateTime? lastSuccessfulSaveTimestamp,
      bool? isUsernameMissing,
      ChatbotMemory? chatbotMemory,
      List<FinanceTransaction>? transactions,
      List<FinanceCategory>? categories,
      List<SavingsGoal>? savingsGoals,
      bool doNotify = true,
      bool doPersist = true
  }) {
    if (lastLoginDate != null) setLastLoginDate(lastLoginDate);
    if (mainTasks != null) setMainTasks(mainTasks);
    if (completedByDay != null) setCompletedByDay(completedByDay);
    if (activeTimers != null) setActiveTimers(activeTimers);
    if (chatbotMemory != null) setChatbotMemory(chatbotMemory);
    if (transactions != null) setTransactions(transactions);
    if (categories != null) setCategories(categories);
    if (savingsGoals != null) setSavingsGoals(savingsGoals);
    
    if (doNotify) notifyListeners();
  }

  // --- Delegated Actions ---

  void addMainTask({required String name, required String description, required String theme, required String colorHex}) => _taskActions.addMainTask(name: name, description: description, theme: theme, colorHex: colorHex);
  void editMainTask(String taskId, {required String name, required String description, required String theme, required String colorHex}) => _taskActions.editMainTask(taskId, name: name, description: description, theme: theme, colorHex: colorHex);
  void logToDailySummary(String type, Map<String, dynamic> data) => _taskActions.logToDailySummary(type, data);
  String addSubtask(String mainTaskId, Map<String, dynamic> subtaskData) => _taskActions.addSubtask(mainTaskId, subtaskData);
  void updateSubtask(String mainTaskId, String subtaskId, Map<String, dynamic> updates) => _taskActions.updateSubtask(mainTaskId, subtaskId, updates);
  bool addSessionToSubtask(String mainTaskId, String subTaskId, DateTime start, DateTime end) => _taskActions.addSessionToSubtask(mainTaskId, subTaskId, start, end);
  void updateSessionInSubtask(String mainTaskId, String subTaskId, String sessionId, DateTime newStart, DateTime newEnd) => _taskActions.updateSessionInSubtask(mainTaskId, subTaskId, sessionId, newStart, newEnd);
  void deleteSessionFromSubtask(String mainTaskId, String subTaskId, String sessionId) => _taskActions.deleteSessionFromSubtask(mainTaskId, subTaskId, sessionId);
  bool completeSubtask(String mainTaskId, String subtaskId, {bool fromSync = false}) => _taskActions.completeSubtask(mainTaskId, subtaskId, fromSync: fromSync);
  void uncompleteSubtask(String mainTaskId, String subtaskId, {bool fromSync = false}) => _taskActions.uncompleteSubtask(mainTaskId, subtaskId, fromSync: fromSync);
  void deleteSubtask(String mainTaskId, String subtaskId) => _taskActions.deleteSubtask(mainTaskId, subtaskId);
  void duplicateCompletedSubtask(String mainTaskId, String subtaskId) => _taskActions.duplicateCompletedSubtask(mainTaskId, subtaskId);
  void addSubSubtask(String mainTaskId, String parentSubtaskId, Map<String, dynamic> subSubtaskData, {String? parentCheckpointId}) => _taskActions.addSubSubtask(mainTaskId, parentSubtaskId, subSubtaskData, parentCheckpointId: parentCheckpointId);
  void updateSubSubtask(String mainTaskId, String parentSubtaskId, String subSubtaskId, Map<String, dynamic> updates) => _taskActions.updateSubSubtask(mainTaskId, parentSubtaskId, subSubtaskId, updates);
  void completeSubSubtask(String mainTaskId, String parentSubtaskId, String subSubtaskId, {bool fromSync = false}) => _taskActions.completeSubSubtask(mainTaskId, parentSubtaskId, subSubtaskId, fromSync: fromSync);
  void uncompleteSubSubtask(String mainTaskId, String parentSubtaskId, String subSubtaskId, {bool fromSync = false}) => _taskActions.uncompleteSubSubtask(mainTaskId, parentSubtaskId, subSubtaskId, fromSync: fromSync);
  void deleteSubSubtask(String mainTaskId, String parentSubtaskId, String subSubtaskId) => _taskActions.deleteSubSubtask(mainTaskId, parentSubtaskId, subSubtaskId);
  void reorderSubtasks(String mainTaskId, int oldIndex, int newIndex) => _taskActions.reorderSubtasks(mainTaskId, oldIndex, newIndex);
  Future<void> recalibrateTimeLogs({bool silent = false}) => _taskActions.recalibrateTimeLogs(silent: silent); 
  void startTimer(String id, String type, String mainTaskId) => _timerActions.startTimer(id, type, mainTaskId);
  void pauseTimer(String id) => _timerActions.pauseTimer(id);
  void logTimerAndReset(String id) => _timerActions.logTimerAndReset(id);
  Future<void> triggerAISubquestGeneration(MainTask mainTask, String generationMode, String userInput, int numSubquests) => _aiGenerationActions.triggerAISubquestGeneration(mainTask, generationMode, userInput, numSubquests);

  // --- Auth & Wrappers ---

  Future<void> loginUser(String email, String password) async => await fb_service.signInWithEmail(email, password);
  Future<void> logoutUser() async => await fb_service.signOut();
  Future<void> signupUser(String email, String password, String username) async {
    final user = await fb_service.signUpWithEmail(email, password);
    if (user != null) {
      await user.updateDisplayName(username);
      await user.reload();
      setCurrentUser(fb_service.firebaseAuthInstance.currentUser);
    }
  }
  Future<void> changePasswordHandler(String pwd) async => await fb_service.changePassword(pwd);
  Future<void> updateUserDisplayName(String name) async {
    if (currentUser != null) {
      await currentUser!.updateDisplayName(name);
      await currentUser!.reload();
      setCurrentUser(fb_service.firebaseAuthInstance.currentUser);
    }
  }

  Future<void> clearAllData() async {
    if (currentUser == null) return;
    await _cloudStorage.deleteUserData(currentUser!.uid);
    await _localStorage.clearState();
    await _resetToInitialState();
    markDirty('settings');
    markDirty('tasks');
    markDirty('history');
    markDirty('reflections');
    markDirty('finance');
    scheduleRealtimeSync();
  }

  Future<void> restoreFromLocalSnapshot(File backupFile) async {
    try {
      final contents = await backupFile.readAsString();
      final data = jsonDecode(contents) as Map<String, dynamic>;
      loadStateFromMap(data);
      scheduleRealtimeSync();
    } catch (e) {
      rethrow;
    }
  }

  void initializeChatbotMemory() {
    notifyListeners(); 
  }

  Future<void> exportReflections() async {
    final data = {'reflectionLogs': reflectionLogs.map((l) => l.toJson()).toList()};
    await _exportService.exportJson(data, 'arcane_reflections');
  }

  Future<void> importReflections() async {
    final data = await _exportService.importJson();
    if (data != null && data['reflectionLogs'] != null) {
      final List<dynamic> logsJson = data['reflectionLogs'];
      final importedLogs = logsJson.map((l) => ReflectionLog.fromJson(l as Map<String, dynamic>)).toList();
      final currentIds = reflectionLogs.map((l) => l.id).toSet();
      final newLogs = importedLogs.where((l) => !currentIds.contains(l.id)).toList();
      if (newLogs.isNotEmpty) {
        setReflectionLogs([...reflectionLogs, ...newLogs]..sort((a,b) => a.timestamp.compareTo(b.timestamp)));
      }
    }
  }

  // --- Gratitude Actions ---
  void updateGratitudeList(List<GratitudeItem> newList) {
    final newMemory = ChatbotMemory.fromJson(chatbotMemory.toJson());
    newMemory.gratitudeList = newList;
    setChatbotMemory(newMemory);
  }

  void updateGratitudeItem(GratitudeItem updatedItem) {
    final currentList = List<GratitudeItem>.from(chatbotMemory.gratitudeList);
    final index = currentList.indexWhere((i) => i.id == updatedItem.id);
    if (index != -1) {
      currentList[index] = updatedItem;
    } else {
      currentList.insert(0, updatedItem);
    }
    updateGratitudeList(currentList);
  }

  // --- Reports Logic ---
  Map<String, dynamic> getLast7DaysData() { 
    final historyStr = HistoryHelper.getSessionHistoryString(mainTasks, 7); 
    final recentReflections = reflectionLogs
        .where((l) => l.timestamp.isAfter(DateTime.now().subtract(const Duration(days: 7))))
        .map((l) => "[${DateFormat('MM-dd').format(l.timestamp)}] ${l.trigger} -> ${l.emotion}")
        .join("\n");
    return {'logs': recentReflections, 'times': historyStr, 'sessions': historyStr};
  }

  Future<List<Map<String, dynamic>>> getArchivedWeeklyReports() async {
    if (currentUser == null) return [];
    return await _cloudStorage.fetchWeeklyReports(currentUser!.uid);
  }

  Future<void> saveWeeklyReport(String date, Map<String, dynamic> data) async {
    if (currentUser != null) {
      await _cloudStorage.saveWeeklyReport(currentUser!.uid, date, data);
    }
  }

  void saveTacticalBriefing(String date, Map<String, dynamic> data) { 
    final newCompletedByDay = Map<String, dynamic>.from(completedByDay);
    final dayData = Map<String, dynamic>.from(newCompletedByDay[date] ?? {});
    dayData['aiBriefing'] = data;
    newCompletedByDay[date] = dayData;
    setCompletedByDay(newCompletedByDay);

    if (currentUser != null) {
      _cloudStorage.saveDailyData(currentUser!.uid, date, 'briefing', data);
    }
  }

  void saveStartDayReport(String date, Map<String, dynamic> data) { 
    final newCompletedByDay = Map<String, dynamic>.from(completedByDay);
    final dayData = Map<String, dynamic>.from(newCompletedByDay[date] ?? {});
    dayData['startDayReport'] = data;
    newCompletedByDay[date] = dayData;
    setCompletedByDay(newCompletedByDay);

    if (currentUser != null) {
      _cloudStorage.saveDailyData(currentUser!.uid, date, 'report', data);
    }
  }

  Map<String, dynamic>? getTacticalBriefing(String date) {
    if (completedByDay[date] != null && completedByDay[date]['aiBriefing'] != null) {
      return completedByDay[date]['aiBriefing'] as Map<String, dynamic>;
    }
    return null;
  }

  Map<String, dynamic>? getStartDayReport(String date) {
    if (completedByDay[date] != null && completedByDay[date]['startDayReport'] != null) {
      return completedByDay[date]['startDayReport'] as Map<String, dynamic>;
    }
    return null;
  }

  Future<Map<String, dynamic>> generateTacticalBriefing(String date, List<ReflectionLog> logs) async { 
    final logsFormatted = logs.map((l) => {'trigger': l.trigger, 'emotion': l.emotion, 'reason': l.reason, 'action': l.action}).toList();
    final recentBriefings = <String>[];
    for (int i=1; i<=3; i++) {
       final d = DateTime.parse(date).subtract(Duration(days: i));
       final dStr = DateFormat('yyyy-MM-dd').format(d);
       final b = getTacticalBriefing(dStr);
       if (b != null && b['summary'] != null) recentBriefings.add(b['summary']);
    }
    
    final result = await _aiService.generateDailySummary(
      reflections: logsFormatted, 
      previousBriefings: recentBriefings, 
      modelCandidates: settings.heavyModels, 
      currentApiKeyIndex: apiKeyIndex, 
      customApiKeys: settings.customApiKeys,
      onNewApiKeyIndex: (idx) => setApiKeyIndex(idx), 
      onLog: (m) => debugPrint(m)
    );

    // Auto-capture newly identified grateful assets
    if (result['grateful_assets'] != null) {
      final extracted = result['grateful_assets'] as List<dynamic>;
      final currentAssets = List<GratitudeItem>.from(chatbotMemory.gratitudeList);
      bool changed = false;
      for (var e in extracted) {
        final map = e as Map<String, dynamic>;
        final name = map['name'] as String? ?? '';
        final type = map['type'] as String? ?? 'resource';
        final why = map['why'] as String? ?? '';
        final what = map['what'] as String? ?? '';
        if (name.isEmpty) continue;

        final existingIdx = currentAssets.indexWhere((a) => a.name.toLowerCase() == name.toLowerCase());
        if (existingIdx != -1) {
          if (why.isNotEmpty && !currentAssets[existingIdx].why.contains(why)) {
            currentAssets[existingIdx].why += (currentAssets[existingIdx].why.isEmpty ? "" : " ") + why;
            changed = true;
          }
          if (what.isNotEmpty && !currentAssets[existingIdx].what.contains(what)) {
             currentAssets[existingIdx].what += (currentAssets[existingIdx].what.isEmpty ? "" : " ") + what;
             changed = true;
          }
        } else {
          currentAssets.insert(0, GratitudeItem(id: const Uuid().v4(), type: type, name: name, why: why, what: what));
          changed = true;
        }
      }
      if (changed) updateGratitudeList(currentAssets);
    }

    // Auto-capture newly identified grateful people
    if (result['grateful_people'] != null) {
      final extracted = result['grateful_people'] as List<dynamic>;
      final currentPeople = List<PersonInfo>.from(chatbotMemory.people);
      bool changed = false;
      for (var e in extracted) {
        final map = e as Map<String, dynamic>;
        final name = map['name'] as String? ?? '';
        final relation = map['relation'] as String? ?? 'Acquaintance';
        if (name.isEmpty) continue;

        final existingIdx = currentPeople.indexWhere((p) => p.name.toLowerCase() == name.toLowerCase());
        if (existingIdx == -1) {
          currentPeople.add(PersonInfo(id: const Uuid().v4(), name: name, relation: relation));
          changed = true;
        }
      }
      if (changed) {
        chatbotMemory.people = currentPeople;
        markDirty('settings');
        scheduleRealtimeSync();
      }
    }

    return result;
  }

  void _cleanOverlappingSessions() {
    bool changed = false;
    final newMainTasks = mainTasks.map((task) {
      return task.copyWith(
        subTasks: task.subTasks.map((sub) {
          if (sub.sessions.length <= 1) return sub;
          final sorted = List<TaskSession>.from(sub.sessions)..sort((a, b) => a.startTime.compareTo(b.startTime));
          final List<TaskSession> cleaned = [sorted.first];
          for (int i = 1; i < sorted.length; i++) {
            final current = sorted[i];
            final previous = cleaned.last;
            if (current.startTime.isBefore(previous.endTime)) {
              changed = true;
              if (current.endTime.isAfter(previous.endTime)) {
                cleaned.removeLast();
                cleaned.add(TaskSession(id: previous.id, startTime: previous.startTime, endTime: current.endTime));
              }
            } else {
              cleaned.add(current);
            }
          }
          if (cleaned.length != sub.sessions.length) {
            final totalSeconds = cleaned.fold(0, (sum, s) => sum + s.durationSeconds);
            return SubTask(
              id: sub.id, name: sub.name, description: sub.description, completed: sub.completed, currentTimeSpent: totalSeconds,
              completedDate: sub.completedDate, isCountable: sub.isCountable, targetCount: sub.targetCount, currentCount: sub.currentCount,
              subSubTasks: sub.subSubTasks, sessions: cleaned, isRecurring: sub.isRecurring, lastCompletedDate: sub.lastCompletedDate, createdAt: sub.createdAt, updatedAt: sub.updatedAt, why: sub.why, what: sub.what, resources: sub.resources,
            );
          }
          return sub;
        }).toList()
      );
    }).toList();

    if (changed) setMainTasks(newMainTasks);
  }

  void _fixTimerAnomalies() {
    // Logic handles in mixin or here if specialized
  }

  Future<void> _handleDailyReset() async {
    final todayStr = helper.getTodayDateString();
    if (lastLoginDate != todayStr) {
      bool changed = false;
      final newMainTasks = mainTasks.map((task) {
        final updatedSubtasks = task.subTasks.map((st) {
          if (st.isRecurring) {
             bool shouldReset = false;
             if (st.completed && st.lastCompletedDate != null) {
                if (DateFormat('yyyy-MM-dd').format(st.lastCompletedDate!) != todayStr) shouldReset = true;
             } else if (st.completed) {
                shouldReset = true;
             }
             if (shouldReset) {
               changed = true;
               return SubTask(
                 id: st.id, name: st.name, description: st.description, completed: false, currentTimeSpent: st.currentTimeSpent,
                 isCountable: st.isCountable, targetCount: st.targetCount, currentCount: 0,
                 subSubTasks: st.subSubTasks.map((s)=> SubSubTask(id: s.id, name: s.name, completed: false, isCountable: s.isCountable, targetCount: s.targetCount)).toList(),
                 sessions: st.sessions, isRecurring: true, lastCompletedDate: st.lastCompletedDate,
                 createdAt: st.createdAt, updatedAt: DateTime.now(), why: st.why, what: st.what, resources: st.resources,
               );
             }
          }
          return st;
        }).toList();
        
        if (task.dailyTimeSpent > 0) {
          changed = true;
          return task.copyWith(subTasks: updatedSubtasks, dailyTimeSpent: 0);
        }
        return task.copyWith(subTasks: updatedSubtasks);
      }).toList();

      setLastLoginDate(todayStr);
      if (changed) setMainTasks(newMainTasks);
    }
  }

  List<bool> getCompletionStatusForCurrentWeek(MainTask task) {
    List<bool> weeklyStatus = List.filled(7, false);
    final now = DateTime.now();
    final currentWeekday = now.weekday;
    final startOffset = settings.startOfWeek;
    int diff = currentWeekday - startOffset;
    if (diff < 0) diff += 7;
    final startOfWeekDate = now.subtract(Duration(days: diff));

    for (int i = 0; i < 7; i++) {
      final targetDate = startOfWeekDate.add(Duration(days: i));
      if (targetDate.isAfter(now)) break;
      final dateStr = DateFormat('yyyy-MM-dd').format(targetDate);
      final dayData = completedByDay[dateStr];
      if (dayData != null && dayData['taskTimes'] != null) {
         final times = dayData['taskTimes'] as Map<String, dynamic>;
         if (times.containsKey(task.id) && (times[task.id] as int) > 0) weeklyStatus[i] = true;
      }
    }
    return weeklyStatus;
  }

  int getYesterdaysTimeForTask(String taskId) {
    final yesterday = DateTime.now().subtract(const Duration(days: 1));
    final dateStr = DateFormat('yyyy-MM-dd').format(yesterday);
    final dayData = completedByDay[dateStr];
    if (dayData != null && dayData['taskTimes'] != null) {
      return (dayData['taskTimes'] as Map<String, dynamic>)[taskId] as int? ?? 0;
    }
    return 0;
  }

  Map<String, dynamic>? findLinkedProjectStepInfo(String targetId) {
    for (var mainTask in mainTasks) {
      for (var project in mainTask.projects) {
        final step = _findStepByTargetId(project.steps, targetId);
        if (step != null) {
          return {'mainTaskId': mainTask.id, 'projectId': project.id, 'projectTitle': project.title, 'stepId': step.id, 'stepTitle': step.title};
        }
      }
    }
    return null;
  }
  
  ProjectStep? _findStepByTargetId(List<ProjectStep> steps, String targetId) {
    for (var step in steps) {
      if (step.linkedTaskId == targetId) return step;
      final found = _findStepByTargetId(step.substeps, targetId);
      if (found != null) return found;
    }
    return null;
  }

  int get7DayWellbeingMomentum(String skillName) {
    final sevenDaysAgo = DateTime.now().subtract(const Duration(days: 7));
    int total = 0;
    for (var log in reflectionLogs) {
      if (log.timestamp.isAfter(sevenDaysAgo)) {
        total += log.xpGained[skillName] ?? 0;
      }
    }
    return total;
  }

  Future<void> syncWeeklyWellbeing() async {
    setLoadingTask("Analyzing Weekly Wellbeing...");
    try {
      final sevenDaysAgo = DateTime.now().subtract(const Duration(days: 7));
      final recentLogs = reflectionLogs.where((l) => l.timestamp.isAfter(sevenDaysAgo)).toList();
      if (recentLogs.isEmpty) {
        throw Exception("No reflection logs in the past 7 days to analyze.");
      }
      
      final logsPayload = recentLogs.map((l) => {
        "log_id": l.id,
        "trigger": l.trigger,
        "emotion": l.emotion,
        "action": l.action,
      }).toList();
      
      final updates = await aiService.evaluateBatchReflections(
        logsPayload: logsPayload,
        modelCandidates: settings.heavyModels, 
        currentApiKeyIndex: apiKeyIndex,
        customApiKeys: settings.customApiKeys,
        onNewApiKeyIndex: (i) => setApiKeyIndex(i),
        onLog: (msg) => debugPrint(msg),
      );
      
      // Update the logs with new XP
      final newLogs = List<ReflectionLog>.from(reflectionLogs);
      bool logsChanged = false;
      for (var update in updates) {
        final logId = update['log_id'];
        final xpMap = Map<String, int>.from(update['xp_allocation'] ?? {});
        final idx = newLogs.indexWhere((l) => l.id == logId);
        if (idx != -1) {
          newLogs[idx] = ReflectionLog(
            id: newLogs[idx].id,
            timestamp: newLogs[idx].timestamp,
            trigger: newLogs[idx].trigger,
            emotion: newLogs[idx].emotion,
            reason: newLogs[idx].reason,
            action: newLogs[idx].action,
            aiFeedback: newLogs[idx].aiFeedback,
            xpGained: xpMap, // Replaced entirely
          );
          logsChanged = true;
        }
      }
      
      if (logsChanged) {
        setReflectionLogs(newLogs);
        
        // Recalculate ALL skill XP to ensure perfect state
        final freshSkills = getBaseWellbeingSkills();
        for (var log in newLogs) {
          log.xpGained.forEach((trait, xp) {
             final s = freshSkills.firstWhereOrNull((x) => x.name.toLowerCase() == trait.toLowerCase());
             if (s != null) s.addXp(xp);
          });
        }
        setSkills(freshSkills);
      }
      
    } finally {
      setLoadingTask(null);
    }
  }

  Future<Map<String, dynamic>> processReflection({required String trigger, required String emotion, required String reason, required String action, DateTime? timestamp}) async {
    final eval = await _aiService.evaluateReflection(
      trigger: trigger, emotion: emotion, reason: reason, action: action,
      modelCandidates: settings.liteModels, 
      customApiKeys: settings.customApiKeys
    );
    final xpGained = Map<String, int>.from(eval['xp_allocation'] ?? {});
    
    final newSkills = List<Skill>.from(skills);
    for (var entry in xpGained.entries) {
      if (entry.value > 0) {
        final skill = newSkills.firstWhereOrNull((s) => s.name.toLowerCase() == entry.key.toLowerCase());
        if (skill != null) skill.addXp(entry.value);
      }
    }
    setSkills(newSkills);

    final log = ReflectionLog(
      id: const Uuid().v4(), timestamp: timestamp ?? DateTime.now(),
      trigger: trigger, emotion: emotion, reason: reason, action: action,
      aiFeedback: eval['feedback'] ?? '', xpGained: xpGained
    );
    setReflectionLogs([...reflectionLogs, log]);
    
    return {'log': log, 'xpGained': xpGained};
  }

  void quickSaveReflection({required String trigger, required String emotion, required String reason, required String action, DateTime? timestamp}) {
    final log = ReflectionLog(
      id: const Uuid().v4(), timestamp: timestamp ?? DateTime.now(),
      trigger: trigger, emotion: emotion, reason: reason, action: action,
      aiFeedback: "Quick Save", xpGained: {}
    );
    setReflectionLogs([...reflectionLogs, log]);
  }

  void updateReflectionLog(String id, {String? trigger, String? emotion, String? reason, String? action}) {
    final index = reflectionLogs.indexWhere((l) => l.id == id);
    if (index != -1) {
      final log = reflectionLogs[index];
      if (trigger != null) log.trigger = trigger;
      if (emotion != null) log.emotion = emotion;
      if (reason != null) log.reason = reason;
      if (action != null) log.action = action;
      setReflectionLogs(List.from(reflectionLogs));
    }
  }

  void deleteReflectionLog(String id) {
    final index = reflectionLogs.indexWhere((l) => l.id == id);
    if (index != -1) {
      final log = reflectionLogs[index];
      final newSkills = List<Skill>.from(skills);
      for (var entry in log.xpGained.entries) {
        final skill = newSkills.firstWhereOrNull((s) => s.name.toLowerCase() == entry.key.toLowerCase());
        if (skill != null) {
           skill.currentXp = (skill.currentXp - entry.value).clamp(0, skill.maxXp);
        }
      }
      setSkills(newSkills);
      
      final newLogs = List<ReflectionLog>.from(reflectionLogs)..removeAt(index);
      setReflectionLogs(newLogs);
    }
  }

  NoraSession? get activeNoraSession {
    if (chatbotMemory.activeNoraSessionId == null) return null;
    return chatbotMemory.noraSessions.firstWhereOrNull((s) => s.id == chatbotMemory.activeNoraSessionId);
  }

  void createNoraSession({required String title, required String tone, required DateTime startDate, required DateTime endDate, String? customContext}) {
    final newSession = NoraSession(id: const Uuid().v4(), title: title, tone: tone, startDate: startDate, endDate: endDate, customContext: customContext);
    final newMemory = ChatbotMemory.fromJson(chatbotMemory.toJson());
    newMemory.noraSessions.add(newSession);
    newMemory.activeNoraSessionId = newSession.id;
    setChatbotMemory(newMemory);
  }

  void switchNoraSession(String sessionId) {
    final newMemory = ChatbotMemory.fromJson(chatbotMemory.toJson());
    newMemory.activeNoraSessionId = sessionId;
    setChatbotMemory(newMemory);
  }

  void deleteNoraSession(String sessionId) {
    final newMemory = ChatbotMemory.fromJson(chatbotMemory.toJson());
    newMemory.noraSessions.removeWhere((s) => s.id == sessionId);
    if (newMemory.activeNoraSessionId == sessionId) {
      newMemory.activeNoraSessionId = newMemory.noraSessions.isNotEmpty ? newMemory.noraSessions.last.id : null;
    }
    setChatbotMemory(newMemory);
  }

  Future<void> sendNoraMessage(String text) async {
    final session = activeNoraSession;
    if (session == null) return;

    final userMsg = ChatbotMessage(id: const Uuid().v4(), text: text, sender: MessageSender.user, timestamp: DateTime.now());
    session.messages.add(userMsg);
    markDirty('settings'); 
    
    try {
      final prompt = "You are ${session.tone}. User: $text";
      final responseText = await _aiService.queryNeuralArchive(
        query: text, logsContext: prompt, 
        modelCandidates: settings.liteModels, 
        currentApiKeyIndex: apiKeyIndex, 
        customApiKeys: settings.customApiKeys, 
        onNewApiKeyIndex: (i) => setApiKeyIndex(i), 
        onLog: (m) {}
      );
      
      final botMsg = ChatbotMessage(id: const Uuid().v4(), text: responseText, sender: MessageSender.bot, timestamp: DateTime.now());
      session.messages.add(botMsg);
      markDirty('settings');
      notifyListeners();
    } catch(e) {
      final errorMsg = ChatbotMessage(id: const Uuid().v4(), text: "Error: $e", sender: MessageSender.bot, timestamp: DateTime.now());
      session.messages.add(errorMsg);
      markDirty('settings');
      notifyListeners();
    }
  }
  
  Future<void> sendMessageToChatbot(String text) async => await sendNoraMessage(text);
  
  void addCustomApiKey(String key) {
    final newKeys = List<String>.from(settings.customApiKeys)..add(key);
    setSettings(settings..customApiKeys = newKeys);
  }
  
  void removeCustomApiKey(String key) {
    final newKeys = List<String>.from(settings.customApiKeys)..remove(key);
    setSettings(settings..customApiKeys = newKeys);
  }
  
  void setJournalPin(String pin) {
    setSettings(settings..journalPin = pin);
  }
}