// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1VzXpHEKVCNfXZAHQ1eWJQo1ruzO1-oY',
    appId: '1:1059901273076:web:86c0ab680c91dc5f843fa1',
    messagingSenderId: '1059901273076',
    projectId: 'task-dominion',
    authDomain: 'task-dominion.firebaseapp.com',
    databaseURL: 'https://task-dominion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-dominion.firebasestorage.app',
    measurementId: 'G-TZTWWCQMCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeZsAoZiV38vUrdzbZP4wBGbOCBGluAZg',
    appId: '1:1059901273076:android:092a770ad41f5234843fa1',
    messagingSenderId: '1059901273076',
    projectId: 'task-dominion',
    databaseURL: 'https://task-dominion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-dominion.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1VzXpHEKVCNfXZAHQ1eWJQo1ruzO1-oY',
    appId: '1:1059901273076:web:fc82a312504729c1843fa1',
    messagingSenderId: '1059901273076',
    projectId: 'task-dominion',
    authDomain: 'task-dominion.firebaseapp.com',
    databaseURL: 'https://task-dominion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-dominion.firebasestorage.app',
    measurementId: 'G-E4Z8MZKKCS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJdGWxFIVjodqOna6Ub4wtpIpx3-mG0Lw',
    appId: '1:1059901273076:ios:681581fd0db8a039843fa1',
    messagingSenderId: '1059901273076',
    projectId: 'task-dominion',
    databaseURL: 'https://task-dominion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-dominion.firebasestorage.app',
    iosBundleId: 'me.ihjas.myapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJdGWxFIVjodqOna6Ub4wtpIpx3-mG0Lw',
    appId: '1:1059901273076:ios:0e00d77480cd44e6843fa1',
    messagingSenderId: '1059901273076',
    projectId: 'task-dominion',
    databaseURL: 'https://task-dominion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-dominion.firebasestorage.app',
    iosBundleId: 'me.ihjas.arcane',
  );

}