// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1VzXpHEKVCNfXZAHQ1eWJQo1ruzO1-oY',
    appId: '1:1059901273076:web:86c0ab680c91dc5f843fa1',
    messagingSenderId: '1059901273076',
    projectId: 'task-dominion',
    authDomain: 'task-dominion.firebaseapp.com',
    databaseURL: 'https://task-dominion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-dominion.firebasestorage.app',
    measurementId: 'G-TZTWWCQMCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeZsAoZiV38vUrdzbZP4wBGbOCBGluAZg',
    appId: '1:1059901273076:android:827b5776e17ef3d1843fa1',
    messagingSenderId: '1059901273076',
    projectId: 'task-dominion',
    databaseURL: 'https://task-dominion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-dominion.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcVfR8s8BoLYP_xS32CY9JWGDYC1Okhh0',
    appId: '1:1059901273076:web:70a683aa039f825c843fa1',
    messagingSenderId: '1059901273076',
    projectId: 'task-dominion',
    authDomain: 'task-dominion.firebaseapp.com',
    databaseURL: 'https://task-dominion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-dominion.firebasestorage.app',
    measurementId: 'G-0EDMDMRYVT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJdGWxFIVjodqOna6Ub4wtpIpx3-mG0Lw',
    appId: '1:1059901273076:ios:418e33b5c673176f843fa1',
    messagingSenderId: '1059901273076',
    projectId: 'task-dominion',
    databaseURL: 'https://task-dominion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-dominion.firebasestorage.app',
    iosBundleId: 'me.ihjas.missions',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJdGWxFIVjodqOna6Ub4wtpIpx3-mG0Lw',
    appId: '1:1059901273076:ios:418e33b5c673176f843fa1',
    messagingSenderId: '1059901273076',
    projectId: 'task-dominion',
    databaseURL: 'https://task-dominion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-dominion.firebasestorage.app',
    iosBundleId: 'me.ihjas.missions',
  );

}